### PR TITLE
Add fb hand tracking sample project

### PR DESCRIPTION
**Pull request by devloglogan**
Adds a sample project showcasing implementations of the OpenXR extensions: XR_FB_hand_tracking_aim, XR_FB_hand_tracking_capsules, and XR_FB_hand_tracking_mesh. Also removes the hand tracking aim demo from the repos general demo project.

This PR depends on https://github.com/GodotVR/godot_openxr_vendors/pull/168 so I'll leave this as a draft until that one is merged.

### CODE REVIEW

**Comment by dsnopek** [comment]
> Also removes the hand tracking aim demo from the repos general demo project.

This will probably cause the XR Simulator test to fail, because the screenshots won't match anymore. Let me know if you want me to record a new VRS file for it, or if you'd like me to show you how :-)

**Comment by devloglogan** [comment]
Updated the VRS file!

**Review by dsnopek — APPROVED** [review]
Thanks! This sample is looking really great in my testing :-)

**Comment by devloglogan** [comment]
Rebased and opened this PR!

**Review by m4gr3d — APPROVED** [review]

**Pull request merged**
