### PR TITLE
Build extension for all supported platforms

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Working on altering build system to include all supported systems.

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
I'm having issues cross compiling on linux, so disabled that for now. Still need to unpack the artifacts to create the final release but waiting for the builds to finish to see what they look like

**Comment by BastiaanOlij** [comment]
Need to do some final tests but I think most of it is working

**Comment by BastiaanOlij** [comment]
OK, as far as i've been told, we can't do a linux ARM64 or RV64 build on github so I'm leaving those out.

But it now build properly for Windows, Mac, Linux x86 and Android as far as I can tell.

**Comment by m4gr3d** [comment]
I'll create a `2.0.2-stable` tag to push the fixes up.

**Pull request merged**
